spring:
  application:
    name: CRUD-SERVICE
  zipkin:
    base-url: http://localhost:8903/
  sleuth:
    sampler:
      probability: 1
  datasource:
    url: "jdbc:mysql://103.235.104.247:3306/poolcardb?autoReconnect=true&useSSL=false"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: pcadmin
    password: Antaheen@4813
    tomcat:
      max-active: 30
      max-idle: 15
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  jmx:
    default-domain: ${spring.application.name}
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        concurrency: 4
        max-concurrency: 8
        retry:
          initial-interval: 5000
server:
  port: ${PORT:8904}
management:
  security:
    enabled: false
logging:
  level:
    root: WARN
    com:
      grayash: DEBUG
    org:
      springframework:
        security: DEBUG
        web: DEBUG
      hibernate: WARN
      apache:
        commons:
          dbcp2: ERROR
  pattern:
    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'